= A2MT Library for Arduino =

The Arduino Application-layer Multi-Tasking (A2MT) library enables the Arduino AVR boards to
run multiple functions using specific schedulers at application layer.

For more information about this library please visit us at
https://sites.google.com/site/arduinoappmt/

== License ==

Copyright (c) Wei-Tsung Su All right reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA